### ISSUE TITLE
Option to change content width not working

### ISSUE THREAD

**Issue by RasterEyes** [GavickPro/Portfolio-Free-WordPress-Theme#34]
I just wanted to mention a strange problem with the theme editor for your GavickPro Portfolio Wordpress theme. In the customize appearance panel there is an option to change the content width under the "Layout & Features" section but when I enter a value other than 700 and hit the save button it doesn't change anything. If I reload the page it will still just say 700 as if I never changed it. I was able to work around this by altering the CSS directly obviously, but it's not the most elegant option to change the content area width and I just thought you may want to know of the issue. I attached a screenshot of the customize appearance panel for clarity. Thanks for the great WordPress theme!

![screen shot 2015-03-29 at 6 08 05 pm](https://cloud.githubusercontent.com/assets/11721416/6898563/f7e15f5a-d6c8-11e4-859c-cad01136474e.png)

**Comment by dziudek** [comment]
Hello,

Yes, we know this issue - it was fixed in v.1.3.0 - you can download it from our repository or just wait when it will be published on wordpress.org

**Comment by RasterEyes** [comment]
Ok great, thanks!

**Comment by RasterEyes** [comment]
Ok great, any idea when it will be published on wordpress.org? Thanks again!

**Comment by dziudek** [comment]
Nobody knows it ;) It depends from the volunteers.

**Comment by RasterEyes** [comment]
Ok, so I downloaded the v.1.3.0 .zip file from GitHub, uploaded the .zip to my WordPress themes, activated the new version, and I'm still having the same problem with the content width customization. It still reverts back to 700 when I try to make it larger. Could I be doing something wrong?

**Comment by dziudek** [comment]
Please make sure that you have fully refreshed your browser cache and you have in the file theme-customizer.php the following fragment:

```php

$wp_customize->add_setting(
	    'portfolio_content_width',
	    array(
	        'default'   => '700',
	        'capability' => 'edit_theme_options',
	        'sanitize_callback' => 'portfolio_intval'
	    )
	);
```

**Comment by RasterEyes** [comment]
That fragment of code is present in theme-customizer.php and I have fully refreshed browser cache but it still isn't saving any new inputs. I noticed it isn't saving any of it at all actually, not even when I change the number of columns or any of the other options. Is there anything else I should look for?

**Comment by dziudek** [comment]
Please send me your back-end access to dziudek[at]gavick[dot]com - I suppose that your issue is connected with other thing than the theme.
